runtime: php55
api_version: 1
threadsafe: true

handlers:   
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js
  
- url: /img
  static_dir: img
  
- url: /src
  static_dir: src
  
- url: /email.php
  Static_files: php/email.php
  Upload: php/email.php

- url: /
  script: index.html
